export default [
  "Feed the",
  "Smile at the",
  "Wink at the",
  "Talk to the",
  "Eat the",
  "Play with the",
  "Decorate the",
  "Drink the",
  "Paint the",
  "Sit on the",
  "Watch the",
  "Drive the",
  "Study the",
  "Shout at the",
  "Grow a new",
  "Kick the",
  "Befriend the",
  "Kiss the",
  "Laugh with the",
  "Meet the",
  "Chuckle at the",
  "Draw the",
  "Build the",
  "Destroy the",
  "Lie with the",
  "Lick the",
  "Pay the"
];
